# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Knuckleheads Smoke N Brew
subtitle: Pflugerville's <b>premier</b> spot for tobacco, tobacco accessories, craft beer, one of a kind craft glass, craft creations and more!
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Knuckleheads is Pflugerville's PREMIER spot for Tobacco, tobacco accessories,
  craft beer, one of a kind craft glass, craft creations and more!! We pride ourselves
  on finding the coolest(and tastiest) things around and bringing them to you!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# To add / remove / change a slideshow image update the list below ensureing to follow the formatting (e.g. "  - file-name.jpg")
# Add the image with the same name in to /assets/images/home-slideshow/
slideshow_images:
  - beer-cases1.jpg
  - pipe-case1.jpg

square_shop_url: "https://my-site-103007-104686.square.site"
online_order_notice: "* For Pickup or Delivery within 5 miles"

# To update the Map, go to https://www.openstreetmap.org/
# Find the location by searching.
# Click the "Share" button on the right side of the screen
# Click the "Include Marker" checkbox
# Adjust marker appropriately
# Click the "HTML" button in the share panel to get an <iframe> snippet
# Take the data held in the src attribute of the <iframe> tag and paste that here as the "map_iframe_src"
map_iframe_src: "https://www.openstreetmap.org/export/embed.html?bbox=-97.61288702487947%2C30.438193826470894%2C-97.61081904172899%2C30.44000683834583&amp;layer=mapnik&amp;marker=30.43910093281755%2C-97.61185261420906"
# Build settings
markdown: kramdown
theme: minima
address:
  line1: 401 FM 685
  line2: Pflugerville, Texas
  phone: (512) 251-6847
instagram_username: knucksnb
facebook_username: knucksnb
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
